services:
    database:
        profiles:
            - prod
            - dev
        build:
            context: ./database
        container_name: database
        ports:
            - 6379:6379
        networks:
            - drag_n_share

    api:
        profiles:
            - prod
        build:
            context: ./api
            dockerfile: ./Dockerfile
        container_name: api
        ports:
            - 7878:7878
        depends_on:
            - database
        networks:
            - drag_n_share

    api-dev:
        profiles:
            - dev
        build:
            context: ./api
            dockerfile: ./Dockerfile.dev
        container_name: api-dev
        ports:
            - 7878:7878
        volumes:
            - ./api/src:/api/src
            - ./api/.env:/api/.env
            - ./api/Cargo.toml:/api/Cargo.toml
            - ./api/Cargo.lock:/api/Cargo.lock
        depends_on:
            - database
        networks:
            - drag_n_share

    transmittor:
        profiles:
            - prod
        build:
            context: ./api
            dockerfile: ./Dockerfile.trns
        container_name: transmittor
        ports:
            - 7879:7879
        depends_on:
            - database
        networks:
            - drag_n_share

    transmittor-dev:
        profiles:
            - dev
        build:
            context: ./api
            dockerfile: ./Dockerfile.trns.dev
        container_name: transmittor-dev
        ports:
            - 7879:7879
        volumes:
            - ./api/src:/transmittor/src
            - ./api/.env:/transmittor/.env
            - ./api/Cargo.toml:/transmittor/Cargo.toml
            - ./api/Cargo.lock:/transmittor/Cargo.lock
        depends_on:
            - database
        networks:
            - drag_n_share
    
    web-app:
        profiles:
            - prod
        build:
            context: ./web_app
        container_name: web-app
        ports:
            - 3000:3000
        depends_on:
            - api
            - transmittor
        networks:
            - drag_n_share
        environment:
            - NUXT_PUBLIC_API_URI=http://api.drag-n-share.com
            - NUXT_PUBLIC_WS_URI=ws://trns.drag-n-share.com
            - NUXT_PUBLIC_TRNS_URI=http://trns.drag-n-share.com
    
    web-app-dev:
        profiles:
            - dev
        build:
            context: ./web_app
            dockerfile: ./Dockerfile.dev
        container_name: web-app-dev
        ports:
            - 3000:3000
        volumes:
            - ./web_app/assets:/app/assets
            - ./web_app/components:/app/components
            - ./web_app/layouts:/app/layouts
            - ./web_app/pages:/app/pages
            - ./web_app/public:/app/public
            - ./web_app/server:/app/server
            - ./web_app/static:/app/static
            - ./web_app/.env:/app/.env
            - ./web_app/error.vue:/app/error.vue
            - ./web_app/nuct.config.ts:/app/nuct.config.ts
            - ./web_app/bun.lockb:/app/bun.lockb
            - ./web_app/json.lock:/app/json.lock
        depends_on:
            - api-dev
            - transmittor-dev
        networks:
            - drag_n_share
        environment:
            - NUXT_PUBLIC_API_URI=http://api.localhost
            - NUXT_PUBLIC_WS_URI=ws://trns.localhost
            - NUXT_PUBLIC_TRNS_URI=http://trns.localhost
    
    nginx:
        profiles:
            - prod
        build:
            context: ./nginx
        container_name: nginx
        ports:
            - 80:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - api
            - transmittor
            - web-app
        networks:
            - drag_n_share
    
    nginx-dev:
        profiles:
            - dev
        build:
            context: ./nginx
            dockerfile: ./Dockerfile.dev
        container_name: nginx-dev
        ports:
            - 80:80
        volumes:
            - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
        depends_on:
            - api-dev
            - transmittor-dev
            - web-app-dev
        networks:
            - drag_n_share

networks:
    drag_n_share:
        driver: bridge
