name: drag_n_share
description: "Drag, Share, Chill"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  localization: ^2.1.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  flutter_native_splash: ^2.4.1

flutter_native_splash:
  color: "#000000" # TODO
  image: "assets/logo.png"
  android_12:
    color: "#000000"
    icon_background_color: "#000000"
    image: "assets/logo.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/logo.png
    - lib/i18n/
