FROM rust:1.82.0 AS build

# new empty shell project
RUN USER=root cargo new --bin api
WORKDIR /api

# auto-reloading on file changes
RUN cargo install cargo-watch

# copy over manifests
COPY ./Cargo.lock ./Cargo.lock
COPY ./Cargo.toml ./Cargo.toml

# build dependencies to cache them
RUN cargo build --release || true

# copy source files
# COPY ./src/lib ./src/lib
# COPY ./src/api.rs ./src/api.rs
COPY ./src ./src
COPY .env ./.env


CMD ["cargo", "watch", "-x", "run --bin api"]