FROM rust:1.82.0 AS build

# new empty shell project
RUN USER=root cargo new --bin transmittor
WORKDIR /transmittor

# auto-reloading on file changes
RUN cargo install cargo-watch

# copy over manifests
COPY ./Cargo.lock ./Cargo.lock
COPY ./Cargo.toml ./Cargo.toml

# build dependencies to cache them
RUN cargo build --release || true

# copy source files
COPY ./src/lib ./src/lib
COPY ./src/transmittor.rs ./src/transmittor.rs
COPY .env ./.env


CMD ["cargo", "watch", "-x", "run --bin transmittor"]