FROM rust:1.80.1 as build

# create a new empty shell project
RUN USER=root cargo new --bin api
WORKDIR /api

# auto-reloading on file changes
RUN cargo install cargo-watch

# copy over your manifests
COPY ./Cargo.lock ./Cargo.lock
COPY ./Cargo.toml ./Cargo.toml

# Build dependencies to cache them
RUN cargo build --release || true

# Copy the source files
COPY ./src ./src
COPY .env ./.env

# Command to start `cargo-watch` to listen for changes and rebuild
CMD ["cargo", "watch", "-x", "run"]